---

- hosts: all
  become: yes

  vars:
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    epel_repofile_path: "/etc/yum.repos.d/epel.repo"

  vars_files:
    - ../env_variables.yml

  tasks:

# Add epel repo
  - name: 1.Check if EPEL repo is already configured.
    stat: path={{ epel_repofile_path }}
    register: epel_repofile_result
 
  - name: 2.Install EPEL repo.
    yum:
      name: "{{ epel_repo_url }}"
      state: present
    register: result
    when: not epel_repofile_result.stat.exists
 
  - name: 3.Import EPEL GPG key.
    rpm_key:
      key: "{{ epel_repo_gpg_key_url }}"
      state: present
    when: not epel_repofile_result.stat.exists

# Install system utilities 
  - name: install system utilities
    yum:
      name: ['tar', 'unzip', 'curl', 'ipset', 'ntp', 'firewalld', 'dnsmasq', 'yum-utils', 'net-tools', 'bind-utils', 'htop', 'vim', 'telnet' ]
      state: latest

# Disabling Selinux
  - name: disable selinux
    selinux: policy=targeted state=permissive

# Configure firewall
# Open all cluster ports for the cluster itself  (TO REVIEW)
  - name: Add master1 role to firewall 
    shell: "iptables -I INPUT -p all -s {{ ipmaster1 }} -j ACCEPT"
  - name: Add master2 role to firewall 
    shell: "iptables -I INPUT -p all -s {{ ipmaster2 }} -j ACCEPT"
  - name: Add master3 role to firewall 
    shell: "iptables -I INPUT -p all -s {{ ipmaster3 }} -j ACCEPT"
  - name: Add gent1 role to firewall 
    shell: "iptables -I INPUT -p all -s {{ ipagent1 }} -j ACCEPT"
  - name: Add gent2 role to firewall 
    shell: "iptables -I INPUT -p all -s {{ ipagent2 }} -j ACCEPT"
  - name: Add gent3 role to firewall 
    shell: "iptables -I INPUT -p all -s {{ ipagent3 }} -j ACCEPT"
